advanced_dbt:
  target: "{{ env_var('DBT_PROFILE_TARGET') }}"
  outputs:
    dev:
      type: snowflake
      account: efruuit-zh04827
      user: test #"{{ env_var('DBT_PROFILE_USER') }}"
      pass: test #"{{ env_var('DBT_PROFILE_PASSWORD') }}"
      role: transformer
      warehouse: transforming
      database: dev
      schema: dbt_lindsay_ci_run
      threads: 1
    production:
      type: snowflake
      account: efruuit-zh04827
      user: test #"{{ env_var('DBT_PROFILE_USER') }}"
      pass: test #"{{ env_var('DBT_PROFILE_PASSWORD') }}"
      role: transformer
      warehouse: transforming
      database: analytics
      schema: dbt_lindsay
      threads: 1
