config:
  use_colors: false
  send_anonymous_usage_stats: false

advanced_dbt:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: efruuit-zh04827
      user: "${{ secrets.SNOWFLAKE_PASSWORD }}"
      pass: "${{ secrets.SNOWFLAKE_PASSWORD }}"
      role: transformer
      database: dev
      warehouse: transforming
      schema: "dbt_ci_run_${{ github.run_number }}"
      threads: 10
