config:
  use_colors: false
  send_anonymous_usage_stats: false

advanced_dbt:
  target: ci
  outputs:
    ci:
      type: snowflake
      account: efruuit-zh04827
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      role: transformer
      database: dev
      warehouse: transforming
      schema: "{{ env_var('CI_SCHEMA') }}"
      threads: 10
