name: dbt CI

on: push

env:
  DBT_PROFILE_TARGET: dev
  DBT_PROFILE_USER: test # {{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: test #{{ secrets.DBT_PROFILE_PASSWORD }}

# concurrency: #remove spaces in front of $
#   group: $ {{ github.workflow }}-$ {{ github.ref }}
#   cancel-in-progress: true

defaults:
 run:
   working-directory: ci_profiles  # this tells GitHub Actions where to find the profiles.yml for Snowflake connection details

jobs:
  run-and-test:
    name: dbt run and test CI checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Remove existing pipenv environment
      run: pipenv --rm || true
    - name: Install pipfile packages
      run: pipenv install
    # - name: Install dbt deps
    #   run: pipenv run dbt deps
    - name: Load seed data
      run: pipenv run dbt seed --target dev --full-refresh
    # - name: Build the models
    #   run: pipenv run dbt run --target dev
    # - name: Execute the tests
    #   run: pipenv run dbt test
    # - name: Run dbt_project_evaluator checks
    #   run: pipenv run dbt build --select package:dbt_project_evaluator dbt_project_evaluator_exceptions
    # - name: Drop the dbt schema
    #   i f: always ()
    #   run: pipenv run dbt run-operation drop_schema --args "{schema_name":" $ {{ env.DBT_CI_SCHEMA }}, database_name":" dev}"
